name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Test on macOS
    runs-on: macOS-latest
    steps:
      - name: Build xcode project
      - run: xcodebuild
